name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710
            sdk_name: -sdk-bcm27xx-bcm2710_
          - arch: aarch64_cortex-a72
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa72
            sdk_name: -sdk-mvebu-cortexa72_
          - arch: aarch64_generic
            sdk_url_path: http://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b
            sdk_name: -sdk-layerscape-armv8_64b_
          - arch: arm_arm1176jzf-s_vfp
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708
            sdk_name: -sdk-bcm27xx-bcm2708_
          - arch: arm_arm926ej-s
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/legacy
            sdk_name: -sdk-at91-legacy_
          - arch: arm_cortex-a15_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic
            sdk_name: -sdk-ipq806x-generic_
          - arch: arm_cortex-a5-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sama5
            sdk_name: -sdk-at91-sama5_
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2709
            sdk_name: -sdk-bcm27xx-bcm2709_
          - arch: arm_cortex-a8_vfpv3
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa8
            sdk_name: -sdk-sunxi-cortexa8_
          - arch: arm_cortex-a9
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic
            sdk_name: -sdk-bcm53xx-generic_
          - arch: arm_cortex-a9_neon
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/imx6/generic
            sdk_name: -sdk-imx6_
          - arch: arm_cortex-a9_vfpv3
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.2/targets/mvebu/cortexa9
            sdk_name: -sdk-19.07.2-mvebu-cortexa9_
          - arch: arm_cortex-a9_vfpv3-d16
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9
            sdk_name: -sdk-mvebu-cortexa9_
          - arch: arm_fa526
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/gemini/generic
            sdk_name: -sdk-gemini_
          - arch: arm_mpcore
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/oxnas/ox820
            sdk_name: -sdk-oxnas-ox820_
          - arch: arm_mpcore_vfp
            sdk_url_path: https://downloads.openwrt.org/releases/19.07.7/targets/cns3xxx/generic
            sdk_name: -sdk-19.07.7-cns3xxx_
          - arch: arm_xscale
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/kirkwood/generic
            sdk_name: -sdk-kirkwood_
          - arch: i386_pentium
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/legacy
            sdk_name: -sdk-x86-legacy_
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/generic
            sdk_name: -sdk-x86-generic_
          - arch: mips64_octeon
            sdk_url_path: http://downloads.openwrt.org/releases/18.06.5/targets/octeon/generic
            sdk_name: -sdk-18.06.5-octeon_
          - arch: mips64_octeonplus
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/octeon/generic
            sdk_name: -sdk-octeon_
          - arch: mipsel_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620
            sdk_name: -sdk-ramips-mt7620_
          - arch: mipsel_24kc_24kf
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/pistachio/generic
            sdk_name: -sdk-pistachio_
          - arch: mipsel_74kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/mips74k
            sdk_name: -sdk-bcm47xx-mips74k_
          - arch: mipsel_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/generic
            sdk_name: -sdk-bcm47xx-generic_
          - arch: mips_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ath79/generic
            sdk_name: -sdk-ath79-generic_
          - arch: mips_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm63xx/generic
            sdk_name: -sdk-bcm63xx-generic_
          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
            sdk_name: -sdk-x86-64_
    
    env:
      PACKAGE_NAME: openwrt-clash
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:${{ env.PACKAGE_NAME }}:${{ env.ARCH }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:${{ env.PACKAGE_NAME }}:${{ env.ARCH }}:cache:
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc
      
      - name: Create Cache Directories
        run: |
          CACHE_DIR_SDK="$CACHE_DIR/sdk"
          CACHE_DIR_DL="$CACHE_DIR/dl"
          CACHE_DIR_FEEDS="$CACHE_DIR/feeds"
          mkdir -p "$CACHE_DIR_SDK"
          mkdir -p "$CACHE_DIR_DL"
          mkdir -p "$CACHE_DIR_FEEDS"
          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Prepare Build Environment
        run: |
          cd "$CACHE_DIR_SDK"
          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
            echo "::error::Can not find ${SDK_NAME} file in sha256sums."
            exit 1
          fi
          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
            wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
            if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
              echo "::error::SDK can not be verified!"
              exit 1
            fi
          fi
          wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
          tar -Jxf "$CACHE_DIR_SDK/$SDK_FILE" -C "$SDK_HOME" --strip=1
          cd "$SDK_HOME"
          [ -d "dl" ] && rm -rf "dl" || true
          [ -d "feeds" ] && rm -rf "feeds" || true
          ln -s "$CACHE_DIR_DL" "dl"
          ln -s "$CACHE_DIR_FEEDS" "feeds"
        
      - name: Build Packages
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update packages
          ./scripts/feeds install packages
          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
          make defconfig
          make package/${PACKAGE_NAME}/{clean,download,compile}
          find "$SDK_HOME/bin" -type f -name "${PACKAGE_NAME}*.ipk" \
           -exec cp -f {} "${{ github.workspace }}" \;
      
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: '*.ipk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
