name: build

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build and Release for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710
            sdk_name: -sdk-bcm27xx-bcm2710_
          - arch: aarch64_cortex-a72
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa72
            sdk_name: -sdk-mvebu-cortexa72_
          - arch: aarch64_generic
            sdk_url_path: http://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b
            sdk_name: -sdk-layerscape-armv8_64b_
          - arch: arm_arm1176jzf-s_vfp
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708
            sdk_name: -sdk-bcm27xx-bcm2708_
          - arch: arm_cortex-a15_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic
            sdk_name: -sdk-ipq806x-generic_
          - arch: arm_cortex-a5-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sama5
            sdk_name: -sdk-at91-sama5_
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2709
            sdk_name: -sdk-bcm27xx-bcm2709_
          - arch: arm_cortex-a8_vfpv3
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa8
            sdk_name: -sdk-sunxi-cortexa8_
          - arch: arm_cortex-a9
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic
            sdk_name: -sdk-bcm53xx-generic_
          - arch: arm_cortex-a9_vfpv3-d16
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9
            sdk_name: -sdk-mvebu-cortexa9_
          - arch: arm_fa526
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/gemini/generic
            sdk_name: -sdk-gemini_
          - arch: arm_mpcore
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/oxnas/ox820
            sdk_name: -sdk-oxnas-ox820_
          - arch: arm_xscale
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/kirkwood/generic
            sdk_name: -sdk-kirkwood_
          - arch: mips64_octeonplus
            sdk_url_path: http://downloads.openwrt.org/snapshots/targets/octeon/generic
            sdk_name: -sdk-octeon_
          - arch: mipsel_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/generic
            sdk_name: -sdk-bcm47xx-generic_
          - arch: mips_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm63xx/generic
            sdk_name: -sdk-bcm63xx-generic_
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/generic
            sdk_name: -sdk-x86-generic_
          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
            sdk_name: -sdk-x86-64_

    env:
      PACKAGE_NAME: clash
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      SDK_NAME: ${{ matrix.sdk_name }}
      ARCH: ${{ matrix.arch }}
      CACHE_DIR: ~/cache

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq gettext libncurses5-dev rsync xsltproc
      - name: Create Directories
        run: |
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV
          echo "SDK_DL_DIR=$(mktemp -d)" >> $GITHUB_ENV
      - name: Prepare Build Environment
        run: |
          cd "$SDK_DL_DIR"
          if ! ( wget -q -O - "$SDK_URL_PATH/sha256sums" | grep -- "$SDK_NAME" > sha256sums.small 2>/dev/null ) ; then
            echo "Can not find ${SDK_NAME} file in sha256sums."
            exit 1
          fi
          SDK_FILE="$(cat sha256sums.small | cut -d' ' -f2 | sed 's/*//g')"
          wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
          if ! sha256sum -c ./sha256sums.small >/dev/null 2>&1 ; then
            echo "SDK can not be verified!"
            exit 1
          fi
          tar -Jxf "$SDK_DL_DIR/$SDK_FILE" -C "$SDK_HOME" --strip=1
      - name: Build Packages
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update packages > /dev/null 2>&1
          ./scripts/feeds install golang > /dev/null 2>&1
          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
          make defconfig > /dev/null 2>&1
          make package/${PACKAGE_NAME}/compile V=s > /dev/null
          CLASH_PATH=$(find "$SDK_HOME/bin" -type f -name "${PACKAGE_NAME}_*.ipk")
          cp -f $CLASH_PATH "${{ github.workspace }}"
          DASHBOARD_PATH=$(find "$SDK_HOME/bin" -type f -name "clash-dashboard_*.ipk")
          if [ "$ARCH" == "x86_64" ]; then cp -f $DASHBOARD_PATH "${{ github.workspace }}"; fi

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
